import Head from 'next/head'

import HistoryView from '../modules/history/view'

const History = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HistoryView />
    </div>
  )
}

export default History
