import Head from 'next/head'
import dynamic from 'next/dynamic'

const HomeView = dynamic(() => import('../modules/home/view'), {
  ssr: false
})

export async function getStaticProps() {
  const isProduction = process.env.NODE_ENV === 'production'
  return {
    props: {
      isProduction
    }
  }
}

const Home = ({ isProduction } : { isProduction: boolean }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeView isProduction={isProduction}/>
    </div>
  )
}

export default Home
