import Head from 'next/head'

import PreferencesView from '../modules/preferences/view'

const Preferences = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PreferencesView />
    </div>
  )
}

export default Preferences
